### ISSUE TITLE
CSS3 Animation 问题咨询

### ISSUE THREAD

**Issue by woota** [woota/frontend-discussion#1]
### 图片一：
![image](https://user-images.githubusercontent.com/7411555/45730265-4c8c7f80-bc03-11e8-9daf-ad8f0448e92f.png)

### 图片二：
![image](https://user-images.githubusercontent.com/7411555/45730321-91b0b180-bc03-11e8-8713-53564bdf8f77.png)

### 图片三：
![image](https://user-images.githubusercontent.com/7411555/45730301-7d6cb480-bc03-11e8-9928-536dc35199e9.png)

## 我有两个问题：
1. 第一张图的那个百分比设定是屏幕距离，还是我设置的移动距离？
2. 我的 `jump` 代码，好像没有正常工作，不明白问题出在哪里？

**Comment by justtio** [comment]
ps：为何去掉第一个drive 的延迟效果，代码就能正常工作了，两者有什么冲突么？

**Comment by woota** [comment]
>第一张图的那个百分比设定是屏幕距离，还是我设置的移动距离？

首先先看一下第三张图片，

![image](https://user-images.githubusercontent.com/7411555/45730566-0c2e0100-bc05-11e8-8b9a-1662d9dca165.png)

这里设置了 `.mario` 这个 `element` 的样式与动画。`position: absolute;` 这是一个 **layout** 的声明，它里面也声明了 `top` 的值，

![image](https://user-images.githubusercontent.com/7411555/45730648-89597600-bc05-11e8-9d32-94914c8fdddf.png)

第一张图中 **jump** 动画操作的 `top` 就是上面👆这张图里面声明的 `top` 值。如果这里对于 `absolute` 的 **layout** 不清楚可以上 **MDN** 看一下相关的文档。

**Comment by justtio** [comment]
一个元素是可以同时声明多个动画的，上面animation中不是有两个时间值么，第一个是动画时长第二个是动画的延迟效果。
我新添的信息里的意思是，去掉jump的延迟时间值，jump就能正常工作了，但是有drive和jump都设延迟的话，就不能不正常工作，不知道为何。

**Comment by woota** [comment]
```html
<div class="mario"></div>
```

```css
@keyframes jump {
  0% { top: 40px; }
  50% { top: 0px; }
  100% { top: 40px; }
}

@keyframes drive {
  from {
    transform: translateX(20px)
  }
  to {
    transform: translateX(600px)
  }
}

.mario {
  width: 100px;
  height: 80px;
  position: absolute;
  top: 40px;
  left: 0px;
  background-color: red;
  animation: drive 3s 1s both infinite linear, jump 0.3s 1s ease;
}
```

**It works for me! [点击查看demo](https://jsfiddle.net/woota/7u361sng/15/)**
